// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add_contact_request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_5frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_5frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_add_5fcontact_5frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_add_5fcontact_5frequest_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_add_5fcontact_5frequest_2eproto;
namespace add_contact_req {
class AddContactRequest;
struct AddContactRequestDefaultTypeInternal;
extern AddContactRequestDefaultTypeInternal _AddContactRequest_default_instance_;
class AddContactRequest_Phone;
struct AddContactRequest_PhoneDefaultTypeInternal;
extern AddContactRequest_PhoneDefaultTypeInternal _AddContactRequest_Phone_default_instance_;
class AddContactRequest_RemarkEntry_DoNotUse;
struct AddContactRequest_RemarkEntry_DoNotUseDefaultTypeInternal;
extern AddContactRequest_RemarkEntry_DoNotUseDefaultTypeInternal _AddContactRequest_RemarkEntry_DoNotUse_default_instance_;
}  // namespace add_contact_req
PROTOBUF_NAMESPACE_OPEN
template<> ::add_contact_req::AddContactRequest* Arena::CreateMaybeMessage<::add_contact_req::AddContactRequest>(Arena*);
template<> ::add_contact_req::AddContactRequest_Phone* Arena::CreateMaybeMessage<::add_contact_req::AddContactRequest_Phone>(Arena*);
template<> ::add_contact_req::AddContactRequest_RemarkEntry_DoNotUse* Arena::CreateMaybeMessage<::add_contact_req::AddContactRequest_RemarkEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace add_contact_req {

enum AddContactRequest_Phone_PhoneType : int {
  AddContactRequest_Phone_PhoneType_MP = 0,
  AddContactRequest_Phone_PhoneType_TEL = 1,
  AddContactRequest_Phone_PhoneType_AddContactRequest_Phone_PhoneType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AddContactRequest_Phone_PhoneType_AddContactRequest_Phone_PhoneType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AddContactRequest_Phone_PhoneType_IsValid(int value);
constexpr AddContactRequest_Phone_PhoneType AddContactRequest_Phone_PhoneType_PhoneType_MIN = AddContactRequest_Phone_PhoneType_MP;
constexpr AddContactRequest_Phone_PhoneType AddContactRequest_Phone_PhoneType_PhoneType_MAX = AddContactRequest_Phone_PhoneType_TEL;
constexpr int AddContactRequest_Phone_PhoneType_PhoneType_ARRAYSIZE = AddContactRequest_Phone_PhoneType_PhoneType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AddContactRequest_Phone_PhoneType_descriptor();
template<typename T>
inline const std::string& AddContactRequest_Phone_PhoneType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AddContactRequest_Phone_PhoneType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AddContactRequest_Phone_PhoneType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AddContactRequest_Phone_PhoneType_descriptor(), enum_t_value);
}
inline bool AddContactRequest_Phone_PhoneType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AddContactRequest_Phone_PhoneType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AddContactRequest_Phone_PhoneType>(
    AddContactRequest_Phone_PhoneType_descriptor(), name, value);
}
// ===================================================================

class AddContactRequest_Phone final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:add_contact_req.AddContactRequest.Phone) */ {
 public:
  inline AddContactRequest_Phone() : AddContactRequest_Phone(nullptr) {}
  ~AddContactRequest_Phone() override;
  explicit PROTOBUF_CONSTEXPR AddContactRequest_Phone(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddContactRequest_Phone(const AddContactRequest_Phone& from);
  AddContactRequest_Phone(AddContactRequest_Phone&& from) noexcept
    : AddContactRequest_Phone() {
    *this = ::std::move(from);
  }

  inline AddContactRequest_Phone& operator=(const AddContactRequest_Phone& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddContactRequest_Phone& operator=(AddContactRequest_Phone&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddContactRequest_Phone& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddContactRequest_Phone* internal_default_instance() {
    return reinterpret_cast<const AddContactRequest_Phone*>(
               &_AddContactRequest_Phone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AddContactRequest_Phone& a, AddContactRequest_Phone& b) {
    a.Swap(&b);
  }
  inline void Swap(AddContactRequest_Phone* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddContactRequest_Phone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddContactRequest_Phone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddContactRequest_Phone>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddContactRequest_Phone& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddContactRequest_Phone& from) {
    AddContactRequest_Phone::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddContactRequest_Phone* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "add_contact_req.AddContactRequest.Phone";
  }
  protected:
  explicit AddContactRequest_Phone(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef AddContactRequest_Phone_PhoneType PhoneType;
  static constexpr PhoneType MP =
    AddContactRequest_Phone_PhoneType_MP;
  static constexpr PhoneType TEL =
    AddContactRequest_Phone_PhoneType_TEL;
  static inline bool PhoneType_IsValid(int value) {
    return AddContactRequest_Phone_PhoneType_IsValid(value);
  }
  static constexpr PhoneType PhoneType_MIN =
    AddContactRequest_Phone_PhoneType_PhoneType_MIN;
  static constexpr PhoneType PhoneType_MAX =
    AddContactRequest_Phone_PhoneType_PhoneType_MAX;
  static constexpr int PhoneType_ARRAYSIZE =
    AddContactRequest_Phone_PhoneType_PhoneType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  PhoneType_descriptor() {
    return AddContactRequest_Phone_PhoneType_descriptor();
  }
  template<typename T>
  static inline const std::string& PhoneType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, PhoneType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function PhoneType_Name.");
    return AddContactRequest_Phone_PhoneType_Name(enum_t_value);
  }
  static inline bool PhoneType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      PhoneType* value) {
    return AddContactRequest_Phone_PhoneType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kNumberFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string number = 1;
  void clear_number();
  const std::string& number() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_number(ArgT0&& arg0, ArgT... args);
  std::string* mutable_number();
  PROTOBUF_NODISCARD std::string* release_number();
  void set_allocated_number(std::string* number);
  private:
  const std::string& _internal_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_number(const std::string& value);
  std::string* _internal_mutable_number();
  public:

  // .add_contact_req.AddContactRequest.Phone.PhoneType type = 2;
  void clear_type();
  ::add_contact_req::AddContactRequest_Phone_PhoneType type() const;
  void set_type(::add_contact_req::AddContactRequest_Phone_PhoneType value);
  private:
  ::add_contact_req::AddContactRequest_Phone_PhoneType _internal_type() const;
  void _internal_set_type(::add_contact_req::AddContactRequest_Phone_PhoneType value);
  public:

  // @@protoc_insertion_point(class_scope:add_contact_req.AddContactRequest.Phone)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr number_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_add_5fcontact_5frequest_2eproto;
};
// -------------------------------------------------------------------

class AddContactRequest_RemarkEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<AddContactRequest_RemarkEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<AddContactRequest_RemarkEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  AddContactRequest_RemarkEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR AddContactRequest_RemarkEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit AddContactRequest_RemarkEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const AddContactRequest_RemarkEntry_DoNotUse& other);
  static const AddContactRequest_RemarkEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const AddContactRequest_RemarkEntry_DoNotUse*>(&_AddContactRequest_RemarkEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "add_contact_req.AddContactRequest.RemarkEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "add_contact_req.AddContactRequest.RemarkEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_add_5fcontact_5frequest_2eproto;
};

// -------------------------------------------------------------------

class AddContactRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:add_contact_req.AddContactRequest) */ {
 public:
  inline AddContactRequest() : AddContactRequest(nullptr) {}
  ~AddContactRequest() override;
  explicit PROTOBUF_CONSTEXPR AddContactRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddContactRequest(const AddContactRequest& from);
  AddContactRequest(AddContactRequest&& from) noexcept
    : AddContactRequest() {
    *this = ::std::move(from);
  }

  inline AddContactRequest& operator=(const AddContactRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddContactRequest& operator=(AddContactRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddContactRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddContactRequest* internal_default_instance() {
    return reinterpret_cast<const AddContactRequest*>(
               &_AddContactRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AddContactRequest& a, AddContactRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AddContactRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddContactRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddContactRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddContactRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddContactRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddContactRequest& from) {
    AddContactRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddContactRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "add_contact_req.AddContactRequest";
  }
  protected:
  explicit AddContactRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef AddContactRequest_Phone Phone;

  // accessors -------------------------------------------------------

  enum : int {
    kPhoneFieldNumber = 3,
    kRemarkFieldNumber = 4,
    kNameFieldNumber = 1,
    kAgeFieldNumber = 2,
  };
  // repeated .add_contact_req.AddContactRequest.Phone phone = 3;
  int phone_size() const;
  private:
  int _internal_phone_size() const;
  public:
  void clear_phone();
  ::add_contact_req::AddContactRequest_Phone* mutable_phone(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::add_contact_req::AddContactRequest_Phone >*
      mutable_phone();
  private:
  const ::add_contact_req::AddContactRequest_Phone& _internal_phone(int index) const;
  ::add_contact_req::AddContactRequest_Phone* _internal_add_phone();
  public:
  const ::add_contact_req::AddContactRequest_Phone& phone(int index) const;
  ::add_contact_req::AddContactRequest_Phone* add_phone();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::add_contact_req::AddContactRequest_Phone >&
      phone() const;

  // map<string, string> remark = 4;
  int remark_size() const;
  private:
  int _internal_remark_size() const;
  public:
  void clear_remark();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_remark() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_remark();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      remark() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_remark();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 age = 2;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:add_contact_req.AddContactRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::add_contact_req::AddContactRequest_Phone > phone_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        AddContactRequest_RemarkEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> remark_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t age_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_add_5fcontact_5frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AddContactRequest_Phone

// string number = 1;
inline void AddContactRequest_Phone::clear_number() {
  _impl_.number_.ClearToEmpty();
}
inline const std::string& AddContactRequest_Phone::number() const {
  // @@protoc_insertion_point(field_get:add_contact_req.AddContactRequest.Phone.number)
  return _internal_number();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddContactRequest_Phone::set_number(ArgT0&& arg0, ArgT... args) {
 
 _impl_.number_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:add_contact_req.AddContactRequest.Phone.number)
}
inline std::string* AddContactRequest_Phone::mutable_number() {
  std::string* _s = _internal_mutable_number();
  // @@protoc_insertion_point(field_mutable:add_contact_req.AddContactRequest.Phone.number)
  return _s;
}
inline const std::string& AddContactRequest_Phone::_internal_number() const {
  return _impl_.number_.Get();
}
inline void AddContactRequest_Phone::_internal_set_number(const std::string& value) {
  
  _impl_.number_.Set(value, GetArenaForAllocation());
}
inline std::string* AddContactRequest_Phone::_internal_mutable_number() {
  
  return _impl_.number_.Mutable(GetArenaForAllocation());
}
inline std::string* AddContactRequest_Phone::release_number() {
  // @@protoc_insertion_point(field_release:add_contact_req.AddContactRequest.Phone.number)
  return _impl_.number_.Release();
}
inline void AddContactRequest_Phone::set_allocated_number(std::string* number) {
  if (number != nullptr) {
    
  } else {
    
  }
  _impl_.number_.SetAllocated(number, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.number_.IsDefault()) {
    _impl_.number_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:add_contact_req.AddContactRequest.Phone.number)
}

// .add_contact_req.AddContactRequest.Phone.PhoneType type = 2;
inline void AddContactRequest_Phone::clear_type() {
  _impl_.type_ = 0;
}
inline ::add_contact_req::AddContactRequest_Phone_PhoneType AddContactRequest_Phone::_internal_type() const {
  return static_cast< ::add_contact_req::AddContactRequest_Phone_PhoneType >(_impl_.type_);
}
inline ::add_contact_req::AddContactRequest_Phone_PhoneType AddContactRequest_Phone::type() const {
  // @@protoc_insertion_point(field_get:add_contact_req.AddContactRequest.Phone.type)
  return _internal_type();
}
inline void AddContactRequest_Phone::_internal_set_type(::add_contact_req::AddContactRequest_Phone_PhoneType value) {
  
  _impl_.type_ = value;
}
inline void AddContactRequest_Phone::set_type(::add_contact_req::AddContactRequest_Phone_PhoneType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:add_contact_req.AddContactRequest.Phone.type)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// AddContactRequest

// string name = 1;
inline void AddContactRequest::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& AddContactRequest::name() const {
  // @@protoc_insertion_point(field_get:add_contact_req.AddContactRequest.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddContactRequest::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:add_contact_req.AddContactRequest.name)
}
inline std::string* AddContactRequest::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:add_contact_req.AddContactRequest.name)
  return _s;
}
inline const std::string& AddContactRequest::_internal_name() const {
  return _impl_.name_.Get();
}
inline void AddContactRequest::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* AddContactRequest::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* AddContactRequest::release_name() {
  // @@protoc_insertion_point(field_release:add_contact_req.AddContactRequest.name)
  return _impl_.name_.Release();
}
inline void AddContactRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:add_contact_req.AddContactRequest.name)
}

// int32 age = 2;
inline void AddContactRequest::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t AddContactRequest::_internal_age() const {
  return _impl_.age_;
}
inline int32_t AddContactRequest::age() const {
  // @@protoc_insertion_point(field_get:add_contact_req.AddContactRequest.age)
  return _internal_age();
}
inline void AddContactRequest::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void AddContactRequest::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:add_contact_req.AddContactRequest.age)
}

// repeated .add_contact_req.AddContactRequest.Phone phone = 3;
inline int AddContactRequest::_internal_phone_size() const {
  return _impl_.phone_.size();
}
inline int AddContactRequest::phone_size() const {
  return _internal_phone_size();
}
inline void AddContactRequest::clear_phone() {
  _impl_.phone_.Clear();
}
inline ::add_contact_req::AddContactRequest_Phone* AddContactRequest::mutable_phone(int index) {
  // @@protoc_insertion_point(field_mutable:add_contact_req.AddContactRequest.phone)
  return _impl_.phone_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::add_contact_req::AddContactRequest_Phone >*
AddContactRequest::mutable_phone() {
  // @@protoc_insertion_point(field_mutable_list:add_contact_req.AddContactRequest.phone)
  return &_impl_.phone_;
}
inline const ::add_contact_req::AddContactRequest_Phone& AddContactRequest::_internal_phone(int index) const {
  return _impl_.phone_.Get(index);
}
inline const ::add_contact_req::AddContactRequest_Phone& AddContactRequest::phone(int index) const {
  // @@protoc_insertion_point(field_get:add_contact_req.AddContactRequest.phone)
  return _internal_phone(index);
}
inline ::add_contact_req::AddContactRequest_Phone* AddContactRequest::_internal_add_phone() {
  return _impl_.phone_.Add();
}
inline ::add_contact_req::AddContactRequest_Phone* AddContactRequest::add_phone() {
  ::add_contact_req::AddContactRequest_Phone* _add = _internal_add_phone();
  // @@protoc_insertion_point(field_add:add_contact_req.AddContactRequest.phone)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::add_contact_req::AddContactRequest_Phone >&
AddContactRequest::phone() const {
  // @@protoc_insertion_point(field_list:add_contact_req.AddContactRequest.phone)
  return _impl_.phone_;
}

// map<string, string> remark = 4;
inline int AddContactRequest::_internal_remark_size() const {
  return _impl_.remark_.size();
}
inline int AddContactRequest::remark_size() const {
  return _internal_remark_size();
}
inline void AddContactRequest::clear_remark() {
  _impl_.remark_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
AddContactRequest::_internal_remark() const {
  return _impl_.remark_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
AddContactRequest::remark() const {
  // @@protoc_insertion_point(field_map:add_contact_req.AddContactRequest.remark)
  return _internal_remark();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
AddContactRequest::_internal_mutable_remark() {
  return _impl_.remark_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
AddContactRequest::mutable_remark() {
  // @@protoc_insertion_point(field_mutable_map:add_contact_req.AddContactRequest.remark)
  return _internal_mutable_remark();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace add_contact_req

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::add_contact_req::AddContactRequest_Phone_PhoneType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::add_contact_req::AddContactRequest_Phone_PhoneType>() {
  return ::add_contact_req::AddContactRequest_Phone_PhoneType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_add_5fcontact_5frequest_2eproto
