// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_enum.proto

#include "test_enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace test_enum {
PROTOBUF_CONSTEXPR Phone::Phone(
    ::_pbi::ConstantInitialized) {}
struct PhoneDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PhoneDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PhoneDefaultTypeInternal() {}
  union {
    Phone _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PhoneDefaultTypeInternal _Phone_default_instance_;
}  // namespace test_enum
static ::_pb::Metadata file_level_metadata_test_5fenum_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_test_5fenum_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_test_5fenum_2eproto = nullptr;

const uint32_t TableStruct_test_5fenum_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::test_enum::Phone, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::test_enum::Phone)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::test_enum::_Phone_default_instance_._instance,
};

const char descriptor_table_protodef_test_5fenum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017test_enum.proto\022\ttest_enum\032\020test_enum2"
  ".proto\"\007\n\005Phone*\034\n\tPhoneType\022\006\n\002MP\020\000\022\007\n\003"
  "TEL\020\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_test_5fenum_2eproto_deps[1] = {
  &::descriptor_table_test_5fenum2_2eproto,
};
static ::_pbi::once_flag descriptor_table_test_5fenum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_test_5fenum_2eproto = {
    false, false, 93, descriptor_table_protodef_test_5fenum_2eproto,
    "test_enum.proto",
    &descriptor_table_test_5fenum_2eproto_once, descriptor_table_test_5fenum_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_test_5fenum_2eproto::offsets,
    file_level_metadata_test_5fenum_2eproto, file_level_enum_descriptors_test_5fenum_2eproto,
    file_level_service_descriptors_test_5fenum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_test_5fenum_2eproto_getter() {
  return &descriptor_table_test_5fenum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_test_5fenum_2eproto(&descriptor_table_test_5fenum_2eproto);
namespace test_enum {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PhoneType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_test_5fenum_2eproto);
  return file_level_enum_descriptors_test_5fenum_2eproto[0];
}
bool PhoneType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Phone::_Internal {
 public:
};

Phone::Phone(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:test_enum.Phone)
}
Phone::Phone(const Phone& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Phone* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:test_enum.Phone)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Phone::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Phone::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Phone::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_test_5fenum_2eproto_getter, &descriptor_table_test_5fenum_2eproto_once,
      file_level_metadata_test_5fenum_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace test_enum
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::test_enum::Phone*
Arena::CreateMaybeMessage< ::test_enum::Phone >(Arena* arena) {
  return Arena::CreateMessageInternal< ::test_enum::Phone >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
